name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: ENV_FILE
          script: |
            cd saas-billing-engine
            printf '%s' "$ENV_FILE" > .env
            git pull origin main
            docker compose up -d --build
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
